version: '3'
services:
    jenkins:
        image: py_jenkins
        container_name: 'jenkins_python'
        ports:
            - '8000:8080'
            - '5000:5000'
        volumes:
            - './jenkins_home:/var/jenkins_home'
            - './cambio:/cambio'
